name: Build and Release

on:
  push:
    tags:
      - 'v*'  # v1.6.1 같은 태그를 푸시하면 자동 실행

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build EXE
      run: |
        pyinstaller HV-L.spec --clean
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/HV-L.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 